Add basics aa1 to master
aichner/coacher pull request #2
Opened 2020-11-10 16:04 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the repository is our template.

**What is the new behavior (if this is a feature change)?**
- It is now possible to login.
- It is now possible to add human ressources and pass on parameters regarding their basic trust values, skills and data.
- It is now possible to sort human ressources based on their skills.

**Other information**:
- The version has been set to `v1.0.0`.

2020-11-10 17:02 UTC, dermrsimon approved these changes
LGTM

2020-11-10 19:50 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-11-10 19:50 UTC, kleberbaum commented on src/App.js
> -            <Navbar />
Could be removed from the imports, cause never used.

2020-11-10 19:50 UTC, kleberbaum commented on src/App.js
> -            <Footer />
Could be removed from the imports, cause never used.

2020-11-10 19:50 UTC, kleberbaum commented on src/Routes.js
> -        <Route exact path="/" component={HomePage} />
Could be removed from the imports, cause never used.

2020-11-10 19:50 UTC, kleberbaum commented on src/components/molecules/CreateContact/index.jsx
> +//#endregion
Please add a newline?

2020-11-10 19:50 UTC, kleberbaum commented on src/components/molecules/CreateContact/index.jsx
> +//#endregion
Please add a newline?

2020-11-10 19:50 UTC, kleberbaum commented on src/components/pages/ProfilePage/index.jsx
> +const AVAILABLE_SKILLS = [
```suggestion
//#region > Config
const AVAILABLE_SKILLS = [
```

2020-11-10 19:50 UTC, kleberbaum commented on src/components/pages/ProfilePage/index.jsx
> +];
```suggestion
];
//#endregion
```

2020-11-10 19:50 UTC, kleberbaum commented on src/components/pages/ProfilePage/index.jsx
> +
```suggestion
```

2020-12-15 12:35 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-12-15 12:36 UTC, merged